SKILLS = [
    # Languages
    "Python",
    "Java",
    "C",
    "C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "Go",
    "Golang",
    "Rust",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "SQL",
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    
    # Frontend Frameworks & Libraries
    "React",
    "React.js",
    "Next.js",
    "Vue.js",
    "Vue",
    "Angular",
    "Svelte",
    "Redux",
    "Tailwind",
    "Tailwind CSS",
    "Bootstrap",
    "jQuery",
    "Sass",
    "Material UI",
    "MUI",
    
    # Backend & Web Frameworks
    "Node.js",
    "Express",
    "Express.js",
    "FastAPI",
    "Django",
    "Flask",
    "Spring Boot",
    "NestJS",
    "Laravel",
    "ASP.NET",
    
    # Databases & Caching
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Postgres",
    "SQLite",
    "Redis",
    "Cassandra",
    "Firebase",
    "Supabase",
    "Prisma",
    "ORMs",
    
    # Cloud, DevOps & Tools
    "Git",
    "GitHub",
    "GitLab",
    "Docker",
    "Kubernetes",
    "K8s",
    "AWS",
    "Azure",
    "GCP",
    "Linux",
    "CI/CD",
    "Jenkins",
    "Terraform",
    "Postman",
    "Swagger",
    "REST API",
    "REST APIs",
    "GraphQL",
    "gRPC",
    "OAuth",
    "JWT",
    
    # Data Science & AI/ML
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "OpenCV",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    
    # Core CS & Tools
    "DSA",
    "Data Structures",
    "Algorithms",
    "DBMS",
    "OOP",
    "Object Oriented Programming",
    "Computer Networks",
    "Operating Systems",
    "System Design",
    "VS Code",
    "PyPDF2",
    "Pydantic"
]